[package]
name = "tera_app"
version = "0.1.0"
publish = false

edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
snapfire_fsr_core = { path = "../../core" }
snapfire_fsr_payload = { path = "../../payload" }
snapfire_fsr_runtime = { path = "../../runtime" }
snapfire_fsr_tera = { path = "../../tera" }
actix-web = "4"
actix-files = "0.6"
fibre_logging = "0.5"
form_urlencoded = "1"
serde_json = { version = "1", features = ["preserve_order"] }
parking_lot = "0.12"
futures-util = "0.3"
tera = { version = "2", features = ["fast"] }
thiserror = "2"
tracing = "0.1"

[dev-dependencies]
futures = "0.3"
