[workspace]
resolver = "2"
members = [
  "compiler",
  "examples/basic_site",
  "fsr/core",
  "fsr/auth",
  "fsr/examples/advanced_tera_app",
  "fsr/payload",
  "fsr/runtime",
  "fsr/service",
  "fsr/session",
  "fsr/tera",
  "rs"
]
exclude = [
]

[workspace.package]
edition = "2024"
license = "MPL-2.0"
authors = ["Norm O <normo.pub@gmail.com>"]