[package]
name = "handbook_react_ts"
version = "0.1.0"
publish = false

edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
snapfire_fsr_host = { path = "../../host" }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

[build-dependencies]
snapfire_fsr_cli = { path = "../../cli" }

[dev-dependencies]
futures = "0.3"
snapfire_fsr_core = { path = "../../core" }
snapfire_fsr_runtime = { path = "../../runtime" }
