// Generated by build.rs: every `ir` below is what the lowerer produced from the
// source beside it under samples/. Edit the samples, not this file.

export interface Sample {
  id: string;
  name: string;
  ts: string;
  ir: string;
  explanation: string;
}

export const SAMPLES: Sample[] = [
  { id: "reduce", name: "Cart counter", ts: "import type { Ctx } from \"@snapfire/fsr\";\n\nexport async function load({ session }: Ctx) {\n  const count = Object.values(session.cart).reduce((n, q) => n + q, 0n);\n  return { count };\n}", ir: "{\n  \"let\": {\n    \"name\": \"count\",\n    \"expr\": {\n      \"reduce\": [\n        {\n          \"values\": {\n            \"session\": \"cart\"\n          }\n        },\n        {\n          \"lit\": {\n            \"int\": 0\n          }\n        },\n        {\n          \"lambda\": {\n            \"params\": [\n              \"n\",\n              \"q\"\n            ],\n            \"body\": {\n              \"arith\": [\n                \"add\",\n                {\n                  \"var\": \"n\"\n                },\n                {\n                  \"var\": \"q\"\n                }\n              ]\n            }\n          }\n        }\n      ]\n    }\n  }\n}", explanation: "TypeScript array methods lower to deterministic nodes the interpreter evaluates in Rust, with no JavaScript heap involved." },
  { id: "guard", name: "Action guard", ts: "import { action, fail } from \"@snapfire/fsr\";\nimport type { ActionCtx } from \"@snapfire/fsr\";\n\nexport const checkout = action(async ({ session, services }: ActionCtx) => {\n  if (Object.keys(session.cart).length === 0) {\n    fail(\"invalid\", \"the cart is empty\");\n  }\n  return await services.shopping.placeOrder({ lines: Object.entries(session.cart) });\n});", ir: "{\n  \"guard\": {\n    \"cond\": {\n      \"compare\": [\n        \"eq\",\n        {\n          \"length\": {\n            \"keys\": {\n              \"session\": \"cart\"\n            }\n          }\n        },\n        {\n          \"lit\": {\n            \"float\": 0.0\n          }\n        }\n      ]\n    },\n    \"kind\": \"invalid\",\n    \"message\": \"the cart is empty\"\n  }\n}", explanation: "A guard that reads nothing external runs before any service socket is opened, so an invalid call never leaves the server." },
  { id: "island", name: "Server island handler", ts: "import { useState } from \"react\";\n\nexport function Disclosure({ label }: { label: string }) {\n  const [open, setOpen] = useState(false);\n  return (\n    <div>\n      <button onClick={() => setOpen(!open)}>{open ? \"Close\" : \"Open\"}</button>\n      {open ? <p>{label}</p> : null}\n    </div>\n  );\n}", ir: "{\n  \"event\": \"click\",\n  \"body\": [\n    {\n      \"return\": {\n        \"object\": [\n          {\n            \"field\": [\n              \"open\",\n              {\n                \"not\": {\n                  \"var\": \"open\"\n                }\n              }\n            ]\n          }\n        ]\n      }\n    }\n  ]\n}", explanation: "A server island's click lowers to pure data: the browser ships no component code and the host answers the round trip with a patch." },
];

export const REFUSED = { ts: "import type { Ctx } from \"@snapfire/fsr\";\n\nexport async function load({ session }: Ctx) {\n  while (session.retries > 0) {\n    retry();\n  }\n  return { status: \"ok\" };\n}", diagnostic: "routes/cart/page.loader.ts:4:3: `while`, a loop whose length the build cannot know\n  a body loops over data it already has: `map`, `filter`, `reduce`, `find` and `for...of`" };
