[package]
name = "advanced_tera_app"
version = "0.1.0"
publish = false

edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
snapfire_fsr_core = { path = "../../core" }
snapfire_fsr_host = { path = "../../host" }
snapfire_fsr_runtime = { path = "../../runtime" }
snapfire_fsr_service = { path = "../../service" }
snapfire_fsr_tera = { path = "../../tera" }
fibre_logging = "0.5"
parking_lot = "0.12"
futures-util = "0.3"
tera = { version = "2", features = ["fast"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }

[dev-dependencies]
snapfire_fsr_payload = { path = "../../payload" }
bytes = "1"
futures = "0.3"
http = "1"
http-body-util = "0.1"
serde_json = "1"
