[package]
name = "snapfire_fsr_macros"
version.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
description = "Derives for SnapFire FSR: the native module attribute."

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
