[package]
name = "chat_react_ts"
version = "0.1.0"
publish = false

edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
parking_lot = "0.12"
snapfire_fsr_core = { path = "../../core" }
snapfire_fsr_host = { path = "../../host" }
snapfire_fsr_runtime = { path = "../../runtime" }
snapfire_fsr_service = { path = "../../service" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync"] }

[build-dependencies]
snapfire_fsr_cli = { path = "../../cli" }

[dev-dependencies]
bytes = "1"
futures = "0.3"
http = "1"
http-body-util = "0.1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
