//! The third server: a warehouse service that speaks only gRPC and is
//! described only by `app/clients/inventory.proto`. Generated by tonic from
//! that file in `build.rs`.

use std::net::SocketAddr;

use tonic::{Request, Response, Status};

pub mod proto {
  tonic::include_proto!("shop.inventory");
}

use proto::inventory_server::{Inventory, InventoryServer};
use proto::{StockLevel, StockRequest};

#[derive(Default)]
pub struct Warehouse;

#[tonic::async_trait]
impl Inventory for Warehouse {
  async fn get_stock(&self, request: Request<StockRequest>) -> Result<Response<StockLevel>, Status> {
    let id = request.into_inner().product_id;
    if !(1..=14).contains(&id) {
      return Err(Status::not_found(format!("no product {id}")));
    }
    let on_hand = [12, 4, 0, 7, 23, 30, 41, 0, 18, 6, 3, 14, 9, 21][(id - 1) as usize];
    let warehouse = if id % 2 == 0 { "north" } else { "south" };
    Ok(Response::new(StockLevel {
      product_id: id,
      on_hand,
      reserved: i32::from(id % 3 == 0),
      warehouse: warehouse.to_owned(),
      bins: vec![format!("{}-{:02}", warehouse.chars().next().unwrap_or('n').to_ascii_uppercase(), id)],
    }))
  }
}

/// Serves the warehouse on `addr`; port 0 picks one, which `bound` reports.
pub async fn serve(addr: SocketAddr) -> std::io::Result<()> {
  let (listener, _) = bind(addr).await?;
  serve_on(listener).await
}

pub async fn bind(addr: SocketAddr) -> std::io::Result<(tokio::net::TcpListener, SocketAddr)> {
  let listener = tokio::net::TcpListener::bind(addr).await?;
  let bound = listener.local_addr()?;
  Ok((listener, bound))
}

pub async fn serve_on(listener: tokio::net::TcpListener) -> std::io::Result<()> {
  let incoming = tokio_stream::wrappers::TcpListenerStream::new(listener);
  tonic::transport::Server::builder()
    .add_service(InventoryServer::new(Warehouse))
    .serve_with_incoming(incoming)
    .await
    .map_err(std::io::Error::other)
}
