(plan 2)
(framework react 18.3.1)
(route /
  (node 0
    shell#document
    (source index)
    (deferred)
    (fallback routes/loading.tsx#default)
    (error routes/error.tsx#default)
    (error-kind not_found routes/error.not-found.tsx#default)
    (cache-key page)
    (slot content (node 1 routes/page.tsx#default (keep modal)))))
(intercept /modal
  (node 0
    shell#document
    (source index)
    (deferred)
    (fallback routes/loading.tsx#default)
    (error routes/error.tsx#default)
    (error-kind not_found routes/error.not-found.tsx#default)
    (cache-key page)
    (slot content (node 1 routes/page.tsx#default (keep modal)))))
(not-found
  (node 0
    shell#document
    (source index)
    (deferred)
    (fallback routes/loading.tsx#default)
    (error routes/error.tsx#default)
    (error-kind not_found routes/error.not-found.tsx#default)
    (cache-key page)
    (slot content (node 1 routes/page.tsx#default (keep modal)))))
(middleware
  (let n $props)
  (if ok ((ret "yes")))
  (if ok ((ret "yes")) ((ret "no")))
  (for-of row rows (do row))
  (for-of row rows)
  (ret out)
  (guard missing NotFound "no such order")
  (session-set cart ("items") next)
  (session-set cart () next)
  (session-del cart ("items"))
  (session-del cart ())
  (act "desk.save" next)
  (do side))
(source index
  lowered
  (module routes/page.loader.ts)
  (export load)
  (reason declared)
  (body
    (let n $props)
    (if ok ((ret "yes")))
    (if ok ((ret "yes")) ((ret "no")))
    (for-of row rows (do row))
    (for-of row rows)
    (ret out)
    (guard missing NotFound "no such order")
    (session-set cart ("items") next)
    (session-set cart () next)
    (session-del cart ("items"))
    (session-del cart ())
    (act "desk.save" next)
    (do side))
  (meta
    (let n $props)
    (if ok ((ret "yes")))
    (if ok ((ret "yes")) ((ret "no")))
    (for-of row rows (do row))
    (for-of row rows)
    (ret out)
    (guard missing NotFound "no such order")
    (session-set cart ("items") next)
    (session-set cart () next)
    (session-del cart ("items"))
    (session-del cart ())
    (act "desk.save" next)
    (do side))
  (store
    (let n $props)
    (if ok ((ret "yes")))
    (if ok ((ret "yes")) ((ret "no")))
    (for-of row rows (do row))
    (for-of row rows)
    (ret out)
    (guard missing NotFound "no such order")
    (session-set cart ("items") next)
    (session-set cart () next)
    (session-del cart ("items"))
    (session-del cart ())
    (act "desk.save" next)
    (do side))
  (paths
    (let n $props)
    (if ok ((ret "yes")))
    (if ok ((ret "yes")) ((ret "no")))
    (for-of row rows (do row))
    (for-of row rows)
    (ret out)
    (guard missing NotFound "no such order")
    (session-set cart ("items") next)
    (session-set cart () next)
    (session-del cart ("items"))
    (session-del cart ())
    (act "desk.save" next)
    (do side)))
(source declared rust)
(action cart.add
  lowered
  (module routes/actions.ts)
  (export add)
  (input AddInput)
  (body
    (let n $props)
    (if ok ((ret "yes")))
    (if ok ((ret "yes")) ((ret "no")))
    (for-of row rows (do row))
    (for-of row rows)
    (ret out)
    (guard missing NotFound "no such order")
    (session-set cart ("items") next)
    (session-set cart () next)
    (session-del cart ("items"))
    (session-del cart ())
    (act "desk.save" next)
    (do side)))
(action cart.clear rust)
(handler route.GET
  GET
  /api
  lowered
  (module routes/route.ts)
  (body
    (let n $props)
    (if ok ((ret "yes")))
    (if ok ((ret "yes")) ((ret "no")))
    (for-of row rows (do row))
    (for-of row rows)
    (ret out)
    (guard missing NotFound "no such order")
    (session-set cart ("items") next)
    (session-set cart () next)
    (session-del cart ("items"))
    (session-del cart ())
    (act "desk.save" next)
    (do side)))
(handler route.POST POST /api rust)
(const src/x.ts#c0 (param id))
(const src/x.ts#c1 (query page))
(const src/x.ts#c10 (now))
(const src/x.ts#c11 $props)
(const src/x.ts#c12 (var nil))
(const src/x.ts#c13 (var #t))
(const src/x.ts#c14 (var 42))
(const src/x.ts#c15 |a b|)
(const src/x.ts#c16 (const src/x.ts#RATE))
(const src/x.ts#c17 nil)
(const src/x.ts#c18 #t)
(const src/x.ts#c19 #f)
(const src/x.ts#c2 (session cart))
(const src/x.ts#c20 -170141183460469231731687303715884105728)
(const src/x.ts#c21 0)
(const src/x.ts#c22 1.5)
(const src/x.ts#c23 2.0)
(const src/x.ts#c24 inf)
(const src/x.ts#c25 -inf)
(const src/x.ts#c26 "")
(const src/x.ts#c27 "a \"quoted\" \\ line\nand a tab\t")
(const src/x.ts#c28 "nil")
(const src/x.ts#c29
  (obj (class "wide") (= ... "a field whose name is a marker") (: "loose") (... rest) (@ "k" val)))
(const src/x.ts#c3 (store theme))
(const src/x.ts#c30 (arr (: "one") (... rest)))
(const src/x.ts#c31 (. row total))
(const src/x.ts#c32 (idx rows 2))
(const src/x.ts#c33 (+ a b))
(const src/x.ts#c34 (- a b))
(const src/x.ts#c35 (* a b))
(const src/x.ts#c36 (/ a b))
(const src/x.ts#c37 (% a b))
(const src/x.ts#c38 (== a b))
(const src/x.ts#c39 (!= a b))
(const src/x.ts#c4 (identity claims sub))
(const src/x.ts#c40 (< a b))
(const src/x.ts#c41 (<= a b))
(const src/x.ts#c42 (> a b))
(const src/x.ts#c43 (>= a b))
(const src/x.ts#c44 (and a b))
(const src/x.ts#c45 (or a b))
(const src/x.ts#c46 (! a))
(const src/x.ts#c47 (?? a b))
(const src/x.ts#c48 (if a b c))
(const src/x.ts#c49 (concat "total " n))
(const src/x.ts#c5 (locale))
(const src/x.ts#c50 (call cart add (id id) (qty 1)))
(const src/x.ts#c51 (call cart clear))
(const src/x.ts#c52 (native img thumb (src src)))
(const src/x.ts#c53 (native-sync img blur))
(const src/x.ts#c54 (fn (n q) n))
(const src/x.ts#c55 (fn () n))
(const src/x.ts#c56 (apply helper a b))
(const src/x.ts#c57 (round n))
(const src/x.ts#c58 (to-fixed n 2))
(const src/x.ts#c59 (encode-uri q))
(const src/x.ts#c6 (path))
(const src/x.ts#c60 (locale-number n))
(const src/x.ts#c61 (range 3))
(const src/x.ts#c62 (omit o "key"))
(const src/x.ts#c63 (ext intl number n))
(const src/x.ts#c64 (map rows f))
(const src/x.ts#c65 (filter rows f))
(const src/x.ts#c66 (reduce rows seed f))
(const src/x.ts#c67 (find rows f))
(const src/x.ts#c68 (find-index rows f))
(const src/x.ts#c69 (some rows f))
(const src/x.ts#c7 (document))
(const src/x.ts#c70 (every rows f))
(const src/x.ts#c71 (entries o))
(const src/x.ts#c72 (keys o))
(const src/x.ts#c73 (values o))
(const src/x.ts#c74 (length rows))
(const src/x.ts#c75 (string n))
(const src/x.ts#c76 (number s))
(const src/x.ts#c77 (bigint n))
(const src/x.ts#c78 (hoist 7 n))
(const src/x.ts#c8 (host))
(const src/x.ts#c9 (input))
(component routes/page.tsx#default
  (shadow closed delegatesfocus clonable serializable)
  (state count open)
  (body
    (let n $props)
    (if ok ((ret "yes")))
    (if ok ((ret "yes")) ((ret "no")))
    (for-of row rows (do row))
    (for-of row rows)
    (ret out)
    (guard missing NotFound "no such order")
    (session-set cart ("items") next)
    (session-set cart () next)
    (session-del cart ("items"))
    (session-del cart ())
    (act "desk.save" next)
    (do side))
  (render
    (<> "plain"
      "<>&\"{}"
      {n}
      (el div
        ((class "wide") (= ... "a field whose name is a marker") (: "loose") (... rest) (@ "k" val))
        "in")
      (el br ())
      (<> "a" "b")
      (<>)
      (if ok "yes" "no")
      (if ok "yes")
      (for (row i) rows {row})
      (let n count {n})
      (comp src/Card.tsx#Card 3 ((title "hi")) "child")
      (comp src/Card.tsx#Card 0 ())
      (island src/Cart.tsx#Cart 4 "idle" "server" ((open #t)) "fallback")
      (island src/Cart.tsx#Cart 0 nil nil ())
      (define-island src/elements/time-ago.ts#default 5 "visible" "back Monday")
      (slot content)
      (baked "<p class=\"x\">" "p" "in")
      (baked "<br/>" nil)))
  (on click
    (let n $props)
    (if ok ((ret "yes")))
    (if ok ((ret "yes")) ((ret "no")))
    (for-of row rows (do row))
    (for-of row rows)
    (ret out)
    (guard missing NotFound "no such order")
    (session-set cart ("items") next)
    (session-set cart () next)
    (session-del cart ("items"))
    (session-del cart ())
    (act "desk.save" next)
    (do side))
  (on submit))
(component routes/layout.tsx#default (tree) (render (slot content)))
(client routes/stars/page.tsx#default
  "src/ui/Stars.tsx:2:17"
  "`.slice()`, which is not a builtin"
  "the builtins are `map`, `filter`, ...")
(client routes/broken/page.tsx#default "routes/broken/page.tsx" "Expected ';'")
