(plan 2)
(route /
  (node 0
    shell#document
    (source index)
    (deferred)
    (fallback routes/loading.tsx#default)
    (error routes/error.tsx#default)
    (cache-key page)
    (slot content (node 1 routes/page.tsx#default (keep modal)))))
(intercept /modal
  (node 0
    shell#document
    (source index)
    (deferred)
    (fallback routes/loading.tsx#default)
    (error routes/error.tsx#default)
    (cache-key page)
    (slot content (node 1 routes/page.tsx#default (keep modal)))))
(not-found
  (node 0
    shell#document
    (source index)
    (deferred)
    (fallback routes/loading.tsx#default)
    (error routes/error.tsx#default)
    (cache-key page)
    (slot content (node 1 routes/page.tsx#default (keep modal)))))
(middleware
  (let n $props)
  (if ok ((ret "yes")))
  (if ok ((ret "yes")) ((ret "no")))
  (for-of row rows (do row))
  (for-of row rows)
  (ret out)
  (guard missing NotFound "no such order")
  (session-set cart ("items") next)
  (session-set cart () next)
  (session-del cart ("items"))
  (session-del cart ())
  (do side))
(source index
  lowered
  (module routes/page.loader.ts)
  (export load)
  (reason declared)
  (body
    (let n $props)
    (if ok ((ret "yes")))
    (if ok ((ret "yes")) ((ret "no")))
    (for-of row rows (do row))
    (for-of row rows)
    (ret out)
    (guard missing NotFound "no such order")
    (session-set cart ("items") next)
    (session-set cart () next)
    (session-del cart ("items"))
    (session-del cart ())
    (do side))
  (meta
    (let n $props)
    (if ok ((ret "yes")))
    (if ok ((ret "yes")) ((ret "no")))
    (for-of row rows (do row))
    (for-of row rows)
    (ret out)
    (guard missing NotFound "no such order")
    (session-set cart ("items") next)
    (session-set cart () next)
    (session-del cart ("items"))
    (session-del cart ())
    (do side))
  (store
    (let n $props)
    (if ok ((ret "yes")))
    (if ok ((ret "yes")) ((ret "no")))
    (for-of row rows (do row))
    (for-of row rows)
    (ret out)
    (guard missing NotFound "no such order")
    (session-set cart ("items") next)
    (session-set cart () next)
    (session-del cart ("items"))
    (session-del cart ())
    (do side)))
(source declared rust)
(action cart.add
  lowered
  (module routes/actions.ts)
  (export add)
  (input AddInput)
  (body
    (let n $props)
    (if ok ((ret "yes")))
    (if ok ((ret "yes")) ((ret "no")))
    (for-of row rows (do row))
    (for-of row rows)
    (ret out)
    (guard missing NotFound "no such order")
    (session-set cart ("items") next)
    (session-set cart () next)
    (session-del cart ("items"))
    (session-del cart ())
    (do side)))
(action cart.clear rust)
(handler route.GET
  GET
  /api
  lowered
  (module routes/route.ts)
  (body
    (let n $props)
    (if ok ((ret "yes")))
    (if ok ((ret "yes")) ((ret "no")))
    (for-of row rows (do row))
    (for-of row rows)
    (ret out)
    (guard missing NotFound "no such order")
    (session-set cart ("items") next)
    (session-set cart () next)
    (session-del cart ("items"))
    (session-del cart ())
    (do side)))
(handler route.POST POST /api rust)
(const src/x.ts#c0 (param id))
(const src/x.ts#c1 (query page))
(const src/x.ts#c10 $props)
(const src/x.ts#c11 (var nil))
(const src/x.ts#c12 (var #t))
(const src/x.ts#c13 (var 42))
(const src/x.ts#c14 |a b|)
(const src/x.ts#c15 (const src/x.ts#RATE))
(const src/x.ts#c16 nil)
(const src/x.ts#c17 #t)
(const src/x.ts#c18 #f)
(const src/x.ts#c19 -170141183460469231731687303715884105728)
(const src/x.ts#c2 (session cart))
(const src/x.ts#c20 0)
(const src/x.ts#c21 1.5)
(const src/x.ts#c22 2.0)
(const src/x.ts#c23 inf)
(const src/x.ts#c24 -inf)
(const src/x.ts#c25 "")
(const src/x.ts#c26 "a \"quoted\" \\ line\nand a tab\t")
(const src/x.ts#c27 "nil")
(const src/x.ts#c28
  (obj (class "wide") (= ... "a field whose name is a marker") (: "loose") (... rest) (@ "k" val)))
(const src/x.ts#c29 (arr (: "one") (... rest)))
(const src/x.ts#c3 (store theme))
(const src/x.ts#c30 (. row total))
(const src/x.ts#c31 (idx rows 2))
(const src/x.ts#c32 (+ a b))
(const src/x.ts#c33 (- a b))
(const src/x.ts#c34 (* a b))
(const src/x.ts#c35 (/ a b))
(const src/x.ts#c36 (% a b))
(const src/x.ts#c37 (== a b))
(const src/x.ts#c38 (!= a b))
(const src/x.ts#c39 (< a b))
(const src/x.ts#c4 (identity claims sub))
(const src/x.ts#c40 (<= a b))
(const src/x.ts#c41 (> a b))
(const src/x.ts#c42 (>= a b))
(const src/x.ts#c43 (and a b))
(const src/x.ts#c44 (or a b))
(const src/x.ts#c45 (! a))
(const src/x.ts#c46 (?? a b))
(const src/x.ts#c47 (if a b c))
(const src/x.ts#c48 (concat "total " n))
(const src/x.ts#c49 (call cart add (id id) (qty 1)))
(const src/x.ts#c5 (locale))
(const src/x.ts#c50 (call cart clear))
(const src/x.ts#c51 (native img thumb (src src)))
(const src/x.ts#c52 (native-sync img blur))
(const src/x.ts#c53 (fn (n q) n))
(const src/x.ts#c54 (fn () n))
(const src/x.ts#c55 (apply helper a b))
(const src/x.ts#c56 (round n))
(const src/x.ts#c57 (to-fixed n 2))
(const src/x.ts#c58 (encode-uri q))
(const src/x.ts#c59 (locale-number n))
(const src/x.ts#c6 (path))
(const src/x.ts#c60 (range 3))
(const src/x.ts#c61 (omit o "key"))
(const src/x.ts#c62 (ext intl number n))
(const src/x.ts#c63 (map rows f))
(const src/x.ts#c64 (filter rows f))
(const src/x.ts#c65 (reduce rows seed f))
(const src/x.ts#c66 (find rows f))
(const src/x.ts#c67 (find-index rows f))
(const src/x.ts#c68 (some rows f))
(const src/x.ts#c69 (every rows f))
(const src/x.ts#c7 (host))
(const src/x.ts#c70 (entries o))
(const src/x.ts#c71 (keys o))
(const src/x.ts#c72 (values o))
(const src/x.ts#c73 (length rows))
(const src/x.ts#c74 (string n))
(const src/x.ts#c75 (number s))
(const src/x.ts#c76 (bigint n))
(const src/x.ts#c77 (hoist 7 n))
(const src/x.ts#c8 (input))
(const src/x.ts#c9 (now))
(component routes/page.tsx#default
  (state count open)
  (body
    (let n $props)
    (if ok ((ret "yes")))
    (if ok ((ret "yes")) ((ret "no")))
    (for-of row rows (do row))
    (for-of row rows)
    (ret out)
    (guard missing NotFound "no such order")
    (session-set cart ("items") next)
    (session-set cart () next)
    (session-del cart ("items"))
    (session-del cart ())
    (do side))
  (render
    (<> "plain"
      "<>&\"{}"
      {n}
      (el div
        ((class "wide") (= ... "a field whose name is a marker") (: "loose") (... rest) (@ "k" val))
        "in")
      (el br ())
      (<> "a" "b")
      (<>)
      (if ok "yes" "no")
      (if ok "yes")
      (for (row i) rows {row})
      (let n count {n})
      (comp src/Card.tsx#Card 3 ((title "hi")) "child")
      (comp src/Card.tsx#Card 0 ())
      (island src/Cart.tsx#Cart 4 "idle" "server" ((open #t)) "fallback")
      (island src/Cart.tsx#Cart 0 nil nil ())
      (slot content)
      (baked "<p class=\"x\">" "p" "in")
      (baked "<br/>" nil)))
  (on click
    (let n $props)
    (if ok ((ret "yes")))
    (if ok ((ret "yes")) ((ret "no")))
    (for-of row rows (do row))
    (for-of row rows)
    (ret out)
    (guard missing NotFound "no such order")
    (session-set cart ("items") next)
    (session-set cart () next)
    (session-del cart ("items"))
    (session-del cart ())
    (do side))
  (on submit))
